service: service-name
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  test:
    handler: handler.initial_function
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux


