service: service-name
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    POWERTOOLS_SERVICE_NAME: ${self:service} # For AWS Lambda Powertools

functions:
  function:
    handler: handler.initial_function
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-uv-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
    useUvRequirements: true
