service: service-name
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}

functions:
  function:
    handler: handler.initial_function
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux


